
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Sidebar from "@/components/sidebar/sidebar";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import EmployeeLayout from "@/components/employeeLayout/EmployeeLayout";
import { StoreProvider } from "@/store/StoreProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let isUserLogged = '';

const getUser = async () => {
  const user = cookies().get('user')?.value || ''
  const token = cookies().get('token')?.value || ''
  if (token && user === 'admin') {
    isUserLogged = user
  }
  if (token && user !== 'admin') {
    isUserLogged = user
  }
}



export default function RootLayout({ children }) {
  getUser()
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {
            isUserLogged === "admin" ? <>
              <Header />
              <div className="flex h-screen ">
                <Sidebar />
                <div className="bg-slate-50 w-full max-w-screen-3xl">
       

                  {children}
                </div>
              </div>
            </> :
              isUserLogged && isUserLogged !== "admin" ?
                <EmployeeLayout children={children} userName={isUserLogged} /> :
                <>
                  <div className="bg-slate-50 w-full max-w-screen-3xl">
                    {children}
                  </div>
                </>
          }

          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          // transition:Bounce
          />
        </body>
      </html >
    </StoreProvider>
  );
}
