import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Sidebar from "@/components/sidebar/sidebar";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ProtectedLayout from "@/components/Protected/Protected";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isLoggedin = false;
export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProtectedLayout />
        {
          isLoggedin && <Header />
        }
        {/* <Header /> */}
        <div className="flex h-screen ">
          {
            isLoggedin && <Sidebar />
          }
          {/* <Sidebar /> */}
          <div className=" bg-slate-50 w-full max-w-screen-3xl">
            {children}
          </div>
        </div>

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        // transition:Bounce
        />
      </body>
    </html >
  );
}
